
[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[main]]
  name = "管理"
  url = "/admin/"
  weight = 30

[[main]]
  name = "文档"
  pageRef = "docs"
  weight = 15

# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 16

[[main]]
  name = "设定"
  pageRef = "world"
  weight = 17

[[main]]
  name = "札记"
  pageRef = "notes"
  weight = 18

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 30

[[footer]]
  name = "Privacy"
  url = "https://external-link"
